name: CI/CD Pipeline

on:
  workflow_dispatch:
    inputs:
      pipeline_type:
        description: 'Select the pipeline type'
        required: true
        default: 'full'
        options:
          - full
          - deploy-only

jobs:
  CI_CDD_Pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      # Full CI/CD pipeline
      - name: Install dependencies
        if: ${{ github.event.inputs.pipeline_type == 'full' }}
        run: npm install

      - name: Run tests
        if: ${{ github.event.inputs.pipeline_type == 'full' }}
        run: npm run test

      - name: SonarQube Scan
        if: ${{ github.event.inputs.pipeline_type == 'full' }}
        uses: SonarSource/sonarqube-scan-action@v5
        with:
          sonarToken: ${{ secrets.SONARCLOUD_TOKEN }}

      # Deployment step
      - name: Install Vercel CLI
        if: ${{ github.event.inputs.pipeline_type == 'full' || github.event.inputs.pipeline_type == 'deploy-only' }}
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        if: ${{ github.event.inputs.pipeline_type == 'full' || github.event.inputs.pipeline_type == 'deploy-only' }}
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        if: ${{ github.event.inputs.pipeline_type == 'full' || github.event.inputs.pipeline_type == 'deploy-only' }}
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        if: ${{ github.event.inputs.pipeline_type == 'full' || github.event.inputs.pipeline_type == 'deploy-only' }}
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
